### ISSUE TITLE
agc_lstm

### ISSUE THREAD

**Issue by shibin2018** [amorim-cleison/snn-sl#8]
Thank you. I want to ask that the  how to use the file models/agc_lstm.py

**Comment by amorim-cleison** [comment]
Hi! Unfortunatelly, this class is still under development. I am working hard in implementing the layer described in the paper https://arxiv.org/abs/1902.09130, but the convolutional and attention operations are not ready yet.

**Comment by shibin2018** [comment]
OK I know. Thank you
----- 原始邮件 -----
发件人：Cleison Amorim <notifications@github.com>
收件人：amorim-cleison/snn-sl <snn-sl@noreply.github.com>
抄送人：shibin2018 <shibin2014@sina.com>,  Author <author@noreply.github.com>
主题：Re: [amorim-cleison/snn-sl] agc_lstm (#8)
日期：2020年04月29日 09点54分


Hi! Unfortunatelly, this class is still under development. I am working hard in implementing the layer described in the paper https://arxiv.org/abs/1902.09130, but the convolutional and attencion operations are not ready yet.
